### Matrix Product

The **matrix product** is an operation in which we have 2 matrices, and we are performing dot products of all combinations of rows from the first matrix and the columns of the 2nd matrix, resulting in a matrix of those atomic **dot products**:

![Matrix Multiplication](./img/diagram%205.png)

To perform a matrix product, the size of the second dimension of the left matrix must match the size of the first dimension of the right matrix. 

For example, if the left matrix has a shape of (5, 4) then the right matrix must match this 4 within the first shape value (4, 7). The shape of the resulting array is always the first dimension of the left array and the second dimension of the right array, (5, 7).

[More reading on Matrix Multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

### Transposition for the Matrix Product

Transposition simply modifies a matrix in a way that its rows become columns and columns become rows:

![Matrix Transposition](./img/diagram%206.png)

Another example:

![Matrix Transposition](./img/diagram%207.png)

### Applying it to NumPy

A row vector is a matrix whose first dimension’s size (the number of rows) equals 1 and the second dimension’s size (the number of columns) equals n — the vector size. In other words, it’s a 1 by n array or array of shape (1, n).

$$ a = \begin{bmatrix} a_1 & a_2 & a_3 & a_4 & \dots & a_n \end{bmatrix} $$

With NumPy and with 3 values, we would define it as:

In [1]:
import numpy as np 

In [2]:
np.array([[1, 2, 3]])

array([[1, 2, 3]])

Note the use of double brackets here. To transform a list into a matrix containing a single row (perform an equivalent operation of turning a vector into row vector), we can put it into a list and create numpy array:

In [3]:
a = [1, 2, 3] 
np.array([a])

array([[1, 2, 3]])

Again, note that we encase a in brackets before converting to an array in this case. Or we can turn it into a 1D array and expand dimensions using one of the NumPy abilities:

In [4]:
a = [1, 2, 3] 
np.expand_dims(np.array(a), axis=0)

array([[1, 2, 3]])

Where np.expand_dims() adds a new dimension at the index of the axis.

A column vector is a matrix where the second dimension’s size equals 1, in other words, it’s an array of shape (n, 1):

$$ b = \begin{bmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \\ \vdots  \\ b_n \end{bmatrix} $$

With NumPy it can be created the same way as a row vector, but needs to be additionally transposed — transposition turns rows into columns and columns into rows:

$$ \begin{bmatrix} b_1 & b_2 & b_3 & b_4 & \dots  & b_n \end{bmatrix}^T
=\begin{bmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \\ \vdots \\ b_n \end{bmatrix}
$$

$$ \begin{bmatrix} b_1 \\ b_2 \\ b_3 \\ b_4 \\ \vdots  \\ b_n \end{bmatrix}^T
= \begin{bmatrix} b_1 & b_2 & b_3 & b_4 & \dots  & b_n \end{bmatrix}
$$

To turn vector b into row vector b, we’ll use the same method that we used to turn vector a into row vector a, then we can perform a transposition on it to make it a column vector b:

$$ b = \begin{bmatrix} 2 & 3 & 4 \end{bmatrix} $$

$$ b^T = \begin{bmatrix} 2 & 3 & 4 \end{bmatrix}^T = \begin{bmatrix} 2 \\ 3 \\ 4 \end{bmatrix} $$

With NumPy code:

In [5]:
a = [1, 2, 3] 
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T

np.dot(a, b)

array([[20]])