### ReLU Activation Function Code

Despite the fancy sounding name, the rectified linear activation function is straightforward to code. It just the maximum of 0 and the value of the input itself.

In [15]:
import numpy as np 

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100] 
output = np.maximum(0, inputs) 

print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


ReLU class definition:

In [16]:
# ReLU activation 
class Activation_ReLU:
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from input
        self.output = np.maximum(0, inputs)

In [17]:
# %load ./Chapter 3 - Adding Layers/3 - Dense Layer Class.ipynb
import numpy as np 

inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100] 
output = np.maximum(0, inputs) 

print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


Importing previous code:

In [23]:
from nnfs.datasets import spiral_data
import numpy as np 
import nnfs

class Layer_Dense:
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases
        
nnfs.init()

Using the class in previous code:

In [24]:
# Create dataset 
X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 output values
dense1 = Layer_Dense(2, 3)

# Create ReLU activation (to be used with Dense layer):
activation1 = Activation_ReLU()

# Perform a forward pass of our training data through this layer
dense1.forward(X)

# Forward pass through activation func.
# Takes in output from previous layer
activation1.forward(dense1.output)

# Let's see output of the first few samples:
print(dense1.output[:5])


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
